version: '3'
services:
  nginx-rtmp:
    platform: "linux/amd64"
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935" # rtmp
      - "1999:1999" # hls
      - "8080:8080" # test server
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./hls:/mnt/hls
      - ./test_server:/mnt/test_server
    restart: always
