"""set user.name not nullable

Revision ID: dbc7ff81be33
Revises: 53c3a49f3045
Create Date: 2023-10-24 11:30:05.161366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dbc7ff81be33'
down_revision: Union[str, None] = '53c3a49f3045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_comment='姓名')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_comment='姓名')
    # ### end Alembic commands ###
